### ISSUE TITLE
apiv3 for wechat pay

### ISSUE THREAD

**Issue by gunsluo** [gunsluo/wechatpay-go#1]

**Comment by gunsluo** [comment]
TODO: 
- [ ] signature/verify
- [ ] encrypt/decrypt cert
- [ ] pay
- [ ] query transaction
- [ ] close transaction
- [ ] notify
- [ ] tradebill
- [ ] fundflowbill

**Comment by clearcodecn** [comment]
/cc @gunsluo 

we should pay attention to office public keys. 
the doc said we should keep update it in 12h

detail see: [https://pay.weixin.qq.com/wiki/doc/apiv3/wechatpay/wechatpay5_1.shtml](https://pay.weixin.qq.com/wiki/doc/apiv3/wechatpay/wechatpay5_1.shtml)

**Comment by clearcodecn** [comment]
#10
